name: 'Commit and Push'
description: 'Automatically commits and pushes changes to the repository.'

inputs:
  author_name:
    description: 'The name of the commit author. Defaults to `github-actions`.'
    required: false
    default: 'qubership-actions[bot]'
  author_email:
    description: 'The email of the commit author. Defaults to `qubership-actions[bot]@qubership.com`.'
    required: false
    default: 'qubership-actions[bot]@qubership.com'
  commit_message:
    description: 'The commit message. Defaults to `Automated commit`.'
    required: false
    default: 'Automated commit'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'git-commit'
  color: 'green'
