name: Extract tag

on:
  workflow_call:
    outputs:
      tag:
        value: ${{ jobs.tag.outputs.tag }}

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug GITHUB_REF
        run: echo "GITHUB_REF = $GITHUB_REF"

      - name: Set tag variable
        id: set_tag
        run: |
          TAG=$(echo "${GITHUB_REF}" | sed -e 's|refs/tags/||' -e 's|refs/heads/||')
          if [ -z "$TAG" ]; then TAG="main"; fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
